package covid.analise.virusanalisator.gui;

public enum UpdateParam {
    SOURCE,
    DESTINATION,
    NUMBER_OF_GENOMES,
    NUMBER_OF_N_GENOMES,
    NUMBER_OF_DOWNLOADED_GENOMES,
    NUMBER_OF_ANALYSED_GENOMES,
    NUMBER_OF_COMBINED_GENOMES,
    NUMBER_OF_RIGHT_GENOMES,
    NUMBER_OF_ERRORS,
    NUMBER_OF_WARNINGS,
    STATUS

}
